export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: require(`@/assets/images/portfolio/skjoineryp.jpg`),
          title: "SK Joinery",
          project: "Done",
          client: "Steve",
          language: "HTML , CSS , JS , VUE",
          preview: "https://www.skjoinery.co.uk",
          previewLink: "https://www.skjoinery.co.uk",
        },
        {
          id: 2,
          img: require(`@/assets/images/portfolio/project-2.jpg`),
          title: "Personal Portfolio Website",
          project: "Done",
          client: "ME",
          language: "HTML , CSS , JS , VUE",
          preview: "https://www.mahmoudsaidi.com/",
          previewLink: "https://www.mahmoudsaidi.com/",
        },
        {
          id: 3,
          img: require(`@/assets/images/portfolio/project-3.jpg`),
          title: "PENDING",
          project: "PENDING ",
          client: "PENDING",
          language: "PENDING",
          preview: "www.instagram.com",
          previewLink: "https://www.instagram.com/thesliderproject/?hl=en",
        },
        {
          id: 4,
          img: require(`@/assets/images/portfolio/project-4.jpg`),
          title: "  Roofing Contractor",
          project: "Done",
          client: "Roonix",
          language: "HTML , CSS , JS",
          preview: "",
          previewLink: "",
        },
        {
          id: 5,
          img: require(`@/assets/images/portfolio/project-5.jpg`),
          title: "Car Valeting Business",
          project: "Done",
          client: "KORSEL",
          language: "HTML , CSS , JS",
          preview: "",
          previewLink: "",
        },
        {
          id: 6,
          img: require(`@/assets/images/portfolio/project-6.jpg`),
          title: "Architectural Design",
          project: "Done",
          client: "Bygge ",
          language: "HTML , CSS , JS",
          preview: "www.themeforest.com",
          previewLink:
            "",
        },
        {
          id: 7,
          img: require(`@/assets/images/portfolio/project-7.jpg`),
          title: "Restabook Restaurant",
          project: "Done",
          client: "Restabook",
          language: "HTML , CSS , JS",
          preview: "",
          previewLink: "",
        },
        {
          id: 8,
          img: require(`@/assets/images/portfolio/project-8.jpg`),
          title: "PENDING",
          project: "PENDING",
          client: "PENDING",
          language: "PENDING",
          preview: "www.facebook.com",
          previewLink: "https://www.facebook.com/ibthemes",
        },
        {
          id: 9,
          img: require(`@/assets/images/portfolio/project-9.jpg`),
          title: "PENDING",
          project: "PENDING",
          client: "PENDING",
          language: "PENDING",
          preview: "www.linkedin.com",
          previewLink:
            "https://www.linkedin.com/in/ib-themes-company-469408207/recent-activity/shares/",
        },
      ],
    };
  },
};
